### ISSUE TITLE
Instructions unclear

### ISSUE THREAD

**Issue by oxr463** [sillsdev/ArtOfReading#3]
> 1) Clone this repository into your own github account.

This sentence makes no sense to me. Are we asking the user to fork the repository on GitHub? Or to clone it locally? I would assume the latter judging by the context, but this sentence itself seems to refer to the former.

**Comment by andrew-polk** [comment]
The sentence after that (directly users to click the green button makes it explicit, but I agree there is some ambiguity in the main statement, so I fixed it.
